---
title: "Offline exercise solutions"
output: 
  html_document:
    toc: false
---

```{r, include=FALSE}
library(knitr)
library(stringr)
knitr::opts_chunk$set(message=FALSE, warning=FALSE, eval=TRUE, echo=FALSE)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
source('reveal.R')
```

\  

```{r, reveal, echo = FALSE, eval = isFALSE(show_text12)}
cat("solutions will be released as the course progresses")
```

\  

To download the solutions for each of the exercises as individual R scripts click the relevant links below. If the code opens in a browser window then right click on the link and select 'save link as' (or similar). 

\  

```{r sol12, results='asis', , eval = isTRUE(show_text12)}
dir <- "exercise_solutions/"
file_name <- list.files(dir) %>%
             sort %>% 
             grep("(exercise_[12]_solution.R)", . , value=TRUE) 

link_name <- file_name %>%
            gsub("\\.R", "", .) %>%
            paste0(., "s") %>%
            gsub("_", " ", .) %>%
            str_to_sentence(.)

paste0("- [", link_name, "](", "exercise_solutions/", file_name, ")") %>%
cat(sep="\n\n")
```

```{r sol34, results='asis', , eval = isTRUE(show_text34)}
dir <- "exercise_solutions/"
file_name <- list.files(dir) %>%
             sort %>% 
             grep("(exercise_[34]_solution.R|exercise_[34]_ggplot_solution.R)", . , value=TRUE) %>% 
             .[c(1,3,2)]

link_name <- file_name %>%
            gsub("\\.R", "", .) %>%
            paste0(., "s") %>%
            gsub("_", " ", .) %>%
            str_to_sentence(.)

paste0("- [", link_name, "](", "exercise_solutions/", file_name, ")") %>%
cat(sep="\n\n")
```

```{r sol56, results='asis', , eval = isTRUE(show_text56)}
dir <- "exercise_solutions/"
file_name <- list.files(dir) %>%
             sort %>% 
             grep("(exercise_[56]_solution.R)", . , value=TRUE) 

link_name <- file_name %>%
            gsub("\\.R", "", .) %>%
            paste0(., "s") %>%
            gsub("_", " ", .) %>%
            str_to_sentence(.)

paste0("- [", link_name, "](", "exercise_solutions/", file_name, ")") %>%
cat(sep="\n\n")
```
