---
title: "PDF version of exercises"
output: 
  html_document:
    toc: false
---

```{r, include=FALSE}
library(knitr)
library(stringr)
knitr::opts_chunk$set(message=FALSE, warning=FALSE, eval=TRUE, echo=FALSE)
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(stringr))
source('reveal.R')
```

\  

Click on the links below to download pdf versions of the exercises. 

\  

```{r, reveal, echo=FALSE, eval = isFALSE(show_exercise)}
cat("Exercises will be released as the course progresses")
```

\  

```{r, results='asis', eval = isTRUE(show_exercise)}
ex_text <- c(": Getting to know R and RStudio", ": Basic R operations", 
             ": Importing and manipulating dataframes", 
             ": Visualising data using base R and lattice graphics",
             ": Basic statistics in R", 
             ": Basic programming in R")

dir <- "exercises"
file_name <- list.files(dir) %>%
              sort %>% 
              grep("[*.zip]", ., value=TRUE)

link_name <- file_name %>%
              gsub("\\.pdf", "", .) %>%
              gsub("_", " ", .) %>%
              str_to_sentence(.)

  paste0("- [", link_name, ex_text, "](", "exercises/", file_name, "){target='_blank'}") %>%
cat(sep="\n\n")
              
```
